### ISSUE TITLE
Possible to use 1-wire?

### ISSUE THREAD

**Issue by bvduijn** [Miceuz/rs485-moist-sensor#10]
Hi Albertas,

I see you also have a version of the moisture sensor using RS-485. I was wondering if it is possible to use 1-wire, more specific. a DS2438Z+ ADC

My idea is to use the 1-wire bus to power the chirps as well. Perhaps not using the chirp function at all but do it centrally and use the moisture sensor purely as a sensor

Hope to hear your thoughts on this.

KR 
Bert

**Comment by Miceuz** [comment]
While this is an interesting idea, but I am not sure if if this is the right part. I would look into implementing one wire protocol directly on attiny. 
DS2438Z is an ADC, but we also need a square wave to excite the sensor.
